# Generated by Django 3.1.4 on 2021-01-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='price',
            new_name='pay',
        ),
    ]
