# Generated by Django 3.1.4 on 2021-01-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210107_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='appointment',
        ),
    ]
