# Generated by Django 3.1.4 on 2021-01-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210106_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nurse',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
